package DBIx::Class::FormFuBuilder;
use strict;
use warnings;

use base 'DBIx::Class';

=head1 NAME

DBIx::Class::FormFuBuilder

=head1 SYNOPSIS

    # ... inside a Schema definition
    # ... preferably generated by DBIx::Class::Schema::Loader
    
    __PACKAGE__->load_components('FormFuBuilder');
    __PACKAGE__->form_fu_extra(column_name => {...});
    
    # at any place you need a form
    my $form = $result_set->generate_form_fu(...)

=head1 METHODS

=cut

=head2 form_fu_extras

specify some extra(s) that get into the {extra}->{form_fu} hash of a column

meaningful things could be:

=over 

=item title

=back

=cut

sub form_fu_extra {
    
}

=head2 generate_form_fu

=cut

sub generate_form_fu {
    my $rs = shift;
    
    warn "calling generate_form_fu with $rs";
}

1;
